[build]
  command = "yarn build"
  publish = "dist"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Origin = "*"
    Access-Control-Max-Age = "3600"
    Content-Type = "*"