openapi: "3.0.0"
basePath: /
host: api.swag.com
info:
  contact:
    name: Etienne Marais
    url: https://<company>.zendesk.com/hc/en-us
  description: The demo API handles all calls to the demo namespace for purposes of illustration.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Second API - From a typical Go Service
paths:
  /second:
    get:
      consumes:
      - application/json
      description: ListDemo will return the demos created by the user making the request.
      operationId: list-demos
      parameters:
      - default: 0
        description: Position in template feed
        in: query
        name: offset
        type: integer
      - default: 20
        description: Number of templates to return
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Bad request
        "401":
          description: Unauthorised
      security:
      - ApiKeyAuth: []
      summary: ListDemo will return the demos created by the user making the request.
      tags:
      - Demo
  /second/{id}:
    post:
      consumes:
      - application/json
      description: CreateDemo will create a new demo.
      operationId: create-demo
      produces:
      - application/json
      responses:
        "201":
          description: Success
        "400":
          description: Bad request
        "401":
          description: Unauthorised
        "404":
          description: Not Found
        "409":
          description: Conflict
        "500":
          description: Internal error
      security:
      - ApiKeyAuth: []
      summary: CreateDemo will create a new demo.
      tags:
      - Demo
schemes:
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: API-Token
    type: apiKey
